spring.application.name=Proj-14_File_Image_Storage_System

#JDBC Oracle Driver Details 
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
#spring.datasource.username=batch46
#spring.datasource.password=root


#JDBC MySQL Driver Details 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql:///mydb
spring.datasource.username=root
spring.datasource.password=root

#JPA-Hibernate properties
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update